from .nodes import NODE_CLASS_MAPPINGS as _LEGACY, NODE_DISPLAY_NAME_MAPPINGS as _LEGACY_NAMES
from .nodes_layered import NODE_CLASS_MAPPINGS as _V2, NODE_DISPLAY_NAME_MAPPINGS as _V2_NAMES

NODE_CLASS_MAPPINGS = {**_V2, **_LEGACY}
NODE_DISPLAY_NAME_MAPPINGS = {**_V2_NAMES, **{k: v + " (legacy)" for k, v in _LEGACY_NAMES.items()}}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
